version: '3'

networks:
  nextcloud_network:
    external: false

services:
  unit:
    build: ./unit
    working_dir: /var/www
    volumes:
      - ./unit/config.json:/docker-entrypoint.d/config.json
      - ./nextcloud/.:/var/www
      - ./unit/php.ini:/etc/php.ini
    ports:
      - 80:80
    networks:
      - nextcloud_network

  postgres:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_DB: "nextcloud"
      POSTGRES_USER: "nextcloud"
      POSTGRES_PASSWORD: "secretnextcloud"
    networks:
      - nextcloud_network

  redis:
      image: redis:alpine
      command: redis-server --appendonly yes
      expose:
        - 6379
      volumes:
          - ./data/redis:/data
      networks:
         - nextcloud_network
